- name: Build Node.js app on AWS EC2
  hosts: all
  remote_user: ec2-user
  vars:
    dir: "{{ APP_PATH }}"
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - git_pull
    - docker_restart
